# GitHub Pages Configuration
remote_theme: pages-themes/merlot
title: AI Fundamentals – Guayerd x IBM
description: Repositorio educativo del curso de Fundamentos de Inteligencia Artificial
author: wigsdev

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude files
exclude:
  - CONTRIBUTING.md
  - LICENSE
  - requirements.txt

# Kramdown configuration
kramdown:
  toc_levels: []
